application: sparkle-hackwat
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin

- url: /
  script: main.py

- url: /images
  static_dir: images

- url: /audio
  static_dir: audio

- url: /.*
  script: main.py
