application: sparkle-hackwat
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin

- url: /
  script: main.py

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: main.py
